### ISSUE TITLE
Please create an example repo

### ISSUE THREAD

**Issue by MarkHerhold** [wallabyjs/atom-wallaby#4] opened 2015-08-28 22:34 UTC
Please create an example repository that shows how wallaby works with a standard node module project.

Thanks

**Comment by ArtemGovorov** [comment] 2015-08-28 23:13
[There's a list of repositories](http://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallaby-js-config-and-other-wallaby-js-recipes) with wallaby configurations. Simple node.js project is  second in the list. There's also a [dedicated docs section](http://wallabyjs.com/docs/integration/node.html) on how to set up a node.js project with wallaby.js Is it enough to get started?

**Comment by MarkHerhold** [comment] 2015-08-29 00:58
Ok. After trying and failing for about 2 hours to get wallaby working on my moderately complex project I created a simple project like the sample there and got it to work. After that was working I again tried with the more complex one and just kept getting a slew of errors. Do you have it working on a more complex project with a lot more files? Like some open source project?

**Comment by MarkHerhold** [comment] 2015-08-29 01:04
PR for docs link https://github.com/wallabyjs/atom-wallaby/pull/5

**Comment by ArtemGovorov** [comment] 2015-08-29 01:27
Yes, wallaby.js core (with IntelliJ IDEs, then with Visual Studio) have been in production since Jan, and we have a few customers using wallaby.js in complex node.js projects with few thousands of tests, most of them are not OSS though, so can't share those. 
From what I can quickly find on GitHub by searching for wallaby.js configs: 
- https://github.com/fixin-platform/backend-core/blob/master/wallaby.js
- https://github.com/TeamMentor/TM_Angular/blob/b22b9b3fb11b9089c7be49d3067093e9d38cc631/wallaby-Node.js

Re: docs - This repo is still quite empty, I didn't have a chance to put many links here, but will do. In a meantime, please have a look into [this main repository](https://github.com/wallabyjs/public/issues), you may find something there as well.

Could you please share your wallaby config and paste some errors that you're getting?

**Comment by MarkHerhold** [comment] 2015-08-29 05:05
Just hooking up a singe directory with no recursive directory searching I get the following error:

```
Wallaby Console: Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'should retrieve the user\'s account specified by ID',
Wallaby Console:   id: 100002,
Wallaby Console:   log: undefined,
Wallaby Console:   filesInvolved: [] }
```

Does Wallaby play well with sinon?

**Comment by ArtemGovorov** [comment] 2015-08-29 05:58
Yes, wallaby.js supports sinon (I have seen quite a few people using it with wallaby).

Regarding the error: it normally happens when some tests end up in the `files` list and the other way around. Do you have any test files that don't follow the `user/*.spec.js` pattern? 

I have quickly changed the calculator sample I shared before to follow your structure, it works for me:

<img width="594" alt="screen shot 2015-08-29 at 3 56 16 pm" src="https://cloud.githubusercontent.com/assets/979966/9560693/8af6ce32-4e66-11e5-8bc2-8aa028dd82c1.png">

If you could share a sample repo where I could reproduce the issue, I may be able to tell what's wrong.

**Comment by MarkHerhold** [comment] 2015-08-29 18:48
I think I may have figured it out. I don't think Wallaby plays well with generator functions and/or the [co-mocha module](https://www.npmjs.com/package/co-mocha).

This **does not** work:
```
'use strict';

require('co-mocha');
var expect = require('chai').expect;

describe('users', function() {
    it('should work', function*() {
        expect(true).to.equal(true);
    });
});
```

This **does** work, notice `function*` --> `function`:
```
'use strict';

require('co-mocha');
var expect = require('chai').expect;

describe('users', function() {
    it('should work', function() {
        expect(true).to.equal(true);
    });
});
```

**Comment by ArtemGovorov** [comment] 2015-08-29 19:03
@MarkHerhold Ah, ok. We do have a working solution for co-mocha, have a look into [this issue](https://github.com/wallabyjs/public/issues/52).

**Comment by ArtemGovorov** [comment] 2015-09-24 07:53
@MarkHerhold Did you make it work? Can I close the issue?

**Comment by MarkHerhold** [comment] 2015-10-04 15:05
I gave up on wallaby for now. I may revisit later.

I still think you need to create a comprehensive example repo, but this is your issue tracker. You can do whatever you like.

**Comment by ArtemGovorov** [comment] 2015-10-05 00:31
Thanks for the update. Please let me know if you decide to try it again in future, I'm happy to help.

Could you please suggest what I could add to our [node.js example repository](https://github.com/wallabyjs/wallaby-node-iojs-sample/) to make it better and more helpful? What was missing for you there that was hard to find/configure? Would love to address your feedback and improve the repo.

**Closed** 2016-08-07 02:42 UTC
