### ISSUE TITLE
Typescript 1.9.0 breaks atom-wallaby

### ISSUE THREAD

**Issue by garycourt** [wallabyjs/atom-wallaby#32] opened 2016-04-07 02:11 UTC
I'm getting the following error when I try to run `atom-wallaby@1.0.7` with `typescript@1.9.0-dev.20160406` on some Typescript code:

```
Postprocessor run failure: e._compiler.getSourceFile is not a function
```

Here is my `wallaby.js` file:

```js
module.exports = function (w) {
  return {
    files: [
      'src/*.ts'
    ],

    tests: [
      'src/tests/*.ts'
    ],

    env: {
      type: 'node'
    },

    compilers: {
      '**/*.ts': w.compilers.typeScript({module: 'commonjs', target: 'es5'})
    }
  };
};
```

This error does not occur if I downgrade Typescript to `1.8.9`.

**Comment by ArtemGovorov** [comment] 2016-04-07 03:02
The issue is fixed in core v1.0.213. The core will be updated automatically in a few minutes, to get the update ASAP, you may [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486).

**Closed by ArtemGovorov** 2016-04-07 03:02 UTC
