### ISSUE TITLE
Uncaught TypeError: (e || "").replace is not a function

### ISSUE THREAD

**Issue by TomYeoman** [wallabyjs/atom-wallaby#58] opened 2017-02-10 16:31 UTC
[Enter steps to reproduce:]

1. This was trigger just by ctrl-z from within my code (It was very basic project, I've attatched a screenshot of the project layout / code which trigger error)

![image](https://cloud.githubusercontent.com/assets/14075632/22834813/6c00d5e6-efae-11e6-8156-5ad5445484d9.png)

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package 1.0.16

### Stack Trace

Uncaught TypeError: (e || "").replace is not a function

```
At C:\Users\Thomas Yeoman\.atom\packages\atom-wallaby\wallaby\client.js:14

TypeError: (e || "").replace is not a function
    at Object._escape (/packages/atom-wallaby/wallaby/client.js:14:26639)
    at Object._line (/packages/atom-wallaby/wallaby/client.js:14:25221)
    at /packages/atom-wallaby/wallaby/client.js:14:26155
    at arrayReduce (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:1441:23)
    at Function.reduce (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:6079:14)
    at Object._test (/packages/atom-wallaby/wallaby/client.js:14:26003)
    at /packages/atom-wallaby/wallaby/client.js:14:24901
    at arrayEach (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:1286:13)
    at Function.forEach (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:5700:11)
    at Object.tests (/packages/atom-wallaby/wallaby/client.js:14:24871)
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:15:1718)
    at b.value (/packages/atom-wallaby/wallaby-atom/index.js:14:30752)
    at b.wrapper (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:2914:56)
    at delayed (/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:6879:27)
```

### Commands

```
     -3:11 core:backspace (input.hidden-input)
     -3:09.7.0 editor:toggle-line-comments (input.hidden-input)
  2x -2:09.1.0 editor:newline (input.hidden-input)
  6x -2:02.8.0 core:backspace (input.hidden-input)
     -2:00.1.0 editor:newline (input.hidden-input)
     -1:56.1.0 core:copy (input.hidden-input)
     -1:55.4.0 core:paste (input.hidden-input)
     -1:51.3.0 core:backspace (input.hidden-input)
     -1:47.6.0 core:copy (input.hidden-input)
  2x -1:42.6.0 editor:newline (input.hidden-input)
     -1:42.4.0 core:paste (input.hidden-input)
  2x -1:37.9.0 core:copy (input.hidden-input)
     -1:34.9.0 core:backspace (input.hidden-input)
     -1:27.8.0 core:paste (input.hidden-input)
  9x -1:26 core:undo (input.hidden-input)
     -0:54.4.0 core:redo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
language-aspx 0.4.0 
atom-wallaby 1.0.16 
cobalt2-syntax 0.5.1 
atom-css-comb 3.1.0 
file-icons 2.0.15 
git-plus 7.2.2 
git-time-machine 1.5.4 
highlight-selected 0.12.0 
javascript-snippets 1.2.1 
language-aspx 0.4.0 
linter 1.11.21 
linter-eslint 8.1.0 
minimap 4.26.8 
monokai-seti 0.7.0 
node_modules undefined 
open-recent 5.0.0 
pigments 0.39.0 
react 0.16.2 
seti-ui 1.6.1 
simple-drag-drop-text 0.3.4 
tabs-to-spaces 1.0.2 
tabs-to-spaces 1.0.2 
```

**Comment by ArtemGovorov** [comment] 2017-02-11 09:06
Thanks for the error, the issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-02-11 09:06 UTC
