### ISSUE TITLE
Wallaby startup never completes

### ISSUE THREAD

**Issue by ctrlplusb** [wallabyjs/atom-wallaby#41] opened 2016-07-14 09:23 UTC
Not sure what has happened.  I have been happily using wallaby for a while now on a large project.  Within the last week or so something has changed though.  Every time I try to start wallaby it never completes the start up process.  I tried to look at the console warning with debug mode enabled and it states all sorts of things like test timeouts and various warnings, but nothing concrete.  

The thing is, if I run standard mocha I get all my tests completed (currently over 300) in under 2 seconds.  No timeouts nothing.  

I thought maybe a recently updated dependency or something was affecting wallaby (like babel) but I had a quick look and it doesn't look like I recently introduced anything untoward.

I am having to run mocha in watch mode for now, but thought it worth logging this issue just in case others are experiencing it too.

If I find the cause I'll update.

**Comment by ArtemGovorov** [comment] 2016-07-14 09:54
I have a suspicion why it may happen, so I just have rolled back few new versions that may have caused the issue. Could you please [force wallaby.js core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and check if it works better for you? Please let me know as soon as you have a chance to try it.

**Comment by ArtemGovorov** [comment] 2016-07-14 10:13
If it doesn't help, please paste some warning messages that it displays with debug mode enabled that you've mentioned.

**Comment by ArtemGovorov** [comment] 2016-07-14 11:49
Actually I went through the recent changes and couldn't find anything that could affect wallaby.js in the way you've described, so I switched the released version back.
However, to exclude the possibility of the issue reason being the recent changes, let's still try the previous version. To do it:
- download the previous version from https://s3.amazonaws.com/wallaby-downloads/wallaby-v1.0.255.zip,
- close Atom,
- open the `user/.atom/packages/atom-wallaby/wallaby` folder and delete its contents,
- extract the downloaded archive to the clean `wallaby` folder,
- open Atom and start wallaby.js on your project.

Note that after a few minutes the wallaby core version will be updated and replaced by the latest, but you should have enough time to try. Let me know if the previous version works for you or not, if not please paste some warning messages that it displays with debug mode enabled that you've mentioned.

**Comment by ArtemGovorov** [comment] 2016-07-14 11:51
If the previous version doesn't work better, please try to create a small sample (hopefully by just leaving one of the tests that times out) and share it.

**Comment by ArtemGovorov** [comment] 2016-07-14 13:38
Ok, I have definitely somethign that could be affecting you. The issue is with the latest **node 6.3** that you may have upgraded to recently. While we are investigating it, you may install **node 6.2.2**, you possibly it side by side with the latest using `nvm` and just specifying the node path for wallaby as [described here](https://wallabyjs.com/docs/intro/install.html#nodejs-1). Note that in your wallaby config you need to delete `env.runner` property (if you have it set).

**Comment by ctrlplusb** [comment] 2016-07-14 13:39
! I did just upgrade in the last week.  :D

Ok, good to know.  I have nvm set up already, so I'll revert back.

**Comment by ctrlplusb** [comment] 2016-07-14 13:39
Thanks for being so prompt in looking into this issue!  You guys are consistently awesome.

**Comment by ArtemGovorov** [comment] 2016-07-15 05:25
The issue with [node 6.3 support](https://github.com/wallabyjs/public/issues/686) is fixed in core v1.0.259.

**Closed by ArtemGovorov** 2016-07-15 05:25 UTC
