### ISSUE TITLE
Uncaught TypeError: a.target.getModel(...).getPath is not a function

### ISSUE THREAD

**Issue by Quimet** [wallabyjs/atom-wallaby#25] opened 2015-12-23 01:48 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-wallaby](https://github.com/wallabyjs/atom-wallaby) package, v1.0.7

### Stack Trace

Uncaught TypeError: a.target.getModel(...).getPath is not a function

```
At /Users/Aneryu/.atom/packages/atom-wallaby/wallaby-atom/index.js:14

TypeError: a.target.getModel(...).getPath is not a function
    at atom-workspace._disposables.add.atom.commands.add.wallaby:select-config-from-editor (/Users/Aneryu/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:1674)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:30.6.0 wallaby:start (atom-text-editor.editor)
  6x -1:28.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -1:22.7.0 tool-panel:unfocus (div.wallaby-tests-view.native-key-bindings)
     -1:14.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:13.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:13.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:53.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:49.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.1.0 wallaby:toggle-panel (atom-text-editor.editor)
     -0:41.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:38.1.0 wallaby:focus-panel (atom-text-editor.editor)
     -0:31.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.5.0 wallaby:show-license (atom-text-editor.editor)
     -0:20.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.9.0 wallaby:select-config-from-editor (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.14.2
atom-wallaby, v1.0.7
linter, v1.11.3

# Dev
No dev packages
```

**Comment by ArtemGovorov** [comment] 2015-12-23 02:18
Thanks for the report. The issue is fixed in wallaby.js Atom plugin 1.0.18 (will be updated automatically).

**Closed by ArtemGovorov** 2015-12-23 02:18 UTC
