### ISSUE TITLE
Error: Cannot find module 'n'

### ISSUE THREAD

**Issue by aaronjensen** [wallabyjs/atom-wallaby#14] opened 2015-09-23 14:19 UTC
This morning, wallaby seems stuck spewing these errors. I have cleared my cache by making changes to the config and restarting wallaby, I have restarted atom and no luck.

Wallaby.js Core v1.0.113

![booking-site - atom 2015-09-23 07-16-04](https://cloud.githubusercontent.com/assets/8588/10047468/2f539eaa-61c3-11e5-85dc-32beb4c21726.png)
![developer tools 2015-09-23 07-18-07](https://cloud.githubusercontent.com/assets/8588/10047483/3fed6214-61c3-11e5-8bd0-808b199dda67.png)

**Comment by aaronjensen** [comment] 2015-09-23 14:27
Repro using this branch: https://github.com/aaronjensen/wallaby-line-number-repro/tree/cannot-find-module-repro

If it doesn't repro, try an `npm update`

It seems to be caused by one spec requiring a file via `inject!` and another requiring the file regularly

**Comment by ArtemGovorov** [comment] 2015-09-23 22:08
Thanks a lot for the repro, the issue is fixed in Atom 1.0.8 + Core 1.0.114.

**Closed by ArtemGovorov** 2015-09-23 22:08 UTC
